In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('homeprices.csv')
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [13]:
dummies = pd.get_dummies(df.town)
dummies
merge = pd.concat([df, dummies], axis = 'columns')
merge

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [19]:
final = merge.drop(['town', 'west windsor'], axis = 1)
final

area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [32]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
X = final.drop(['price'], axis = 'columns')
y = final.price
model.fit(X, y)
model.predict([[2800, 0, 1]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([590775.63964739])

In [55]:
model.predict([[3400, 0, 0]])

array([87543575.57514073])

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dle = df
le.fit_transform(dle.town)
dle.town = le.fit_transform(dle.town)
dle

NameError: name 'df' is not defined

In [50]:
X = dle[['town', 'area']].values
y = dle.price.values


In [1]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')
X = ohe.fit_transform(x)
X = X[:, 1:]
X

NameError: name 'x' is not defined

In [52]:
model.fit(X, y)

LinearRegression()

In [53]:
model.predict([[1, 0,2800]])

array([590775.63964739])

In [56]:
model.predict([[0, 0, 3400]])

array([641227.69296925])