In [1]:
import pandas as pd
import numpy as np
from sklearn import svm, datasets
iris = datasets.load_iris()
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [2]:
data = pd.DataFrame(iris.data, columns = iris.feature_names)
data['flower'] = iris.target
data['flower'] = data['flower'].apply(lambda x: iris.target_names[x])
data.drop(['flower'], axis = 'columns', inplace = True)

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data, iris.target, test_size = 0.2)

In [4]:
model = svm.SVC(kernel = 'rbf', C = 20, gamma = 'auto')
model.fit(x_train, y_train)
model.score(x_test, y_test)

1.0

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
cross_val_score(svm.SVC(kernel = 'linear', C = 1, gamma = 'auto'), iris.data, iris.target, cv =6)

array([0.96, 1.  , 0.96, 0.96, 1.  , 1.  ])

In [7]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 10, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score(svm.SVC(kernel = 'rbf', C = 20, gamma = 'auto'), iris.data, iris.target, cv = 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
kernels = ['linear', 'rbf']
C = [1, 10, 20]
avg_score = {}

for k in kernels:
    for c in C:
        cv_score = cross_val_score(svm.SVC(kernel = k, C = c, gamma = 'auto'), iris.data, iris.target, cv = 6)
        print(cv_score)
        avg_score[k + '_' + str(c)] = np.average(cv_score)
       


[0.96 1.   0.96 0.96 1.   1.  ]
[1.   1.   0.92 0.92 0.96 1.  ]
[1.   1.   0.92 0.92 0.96 1.  ]
[0.96 1.   0.96 0.92 0.96 1.  ]
[0.96 1.   0.92 0.92 0.96 1.  ]
[0.96 1.   0.88 0.92 0.96 1.  ]


In [10]:
cv_score

array([0.96, 1.  , 0.88, 0.92, 0.96, 1.  ])

In [11]:
avg_score

{'linear_1': 0.98,
 'linear_10': 0.9666666666666667,
 'linear_20': 0.9666666666666667,
 'rbf_1': 0.9666666666666667,
 'rbf_10': 0.96,
 'rbf_20': 0.9533333333333333}

In [12]:
from sklearn.model_selection import GridSearchCV
gscv = GridSearchCV(svm.SVC(gamma = 'auto'), {
    'C': [1, 10, 20],
    'kernel': ['rbf', 'linear']
}, cv = 5, return_train_score = False
)
gscv.fit(x_train, y_train)
gscv.score(x_test, y_test)

1.0

In [141]:
gscv.cv_results_

{'mean_fit_time': array([0.00162506, 0.00172124, 0.00180736, 0.00312986, 0.        ,
        0.00312047]),
 'std_fit_time': array([0.00199069, 0.00120116, 0.00039379, 0.00625973, 0.        ,
        0.00624094]),
 'mean_score_time': array([0.00478787, 0.0011992 , 0.00080004, 0.        , 0.        ,
        0.00312481]),
 'std_score_time': array([0.00601564, 0.00074751, 0.00040002, 0.        , 0.        ,
        0.00624962]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [142]:
data = pd.DataFrame(gscv.cv_results_)

In [143]:
data

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001625      0.001991         0.004788        0.006016       1   
1       0.001721      0.001201         0.001199        0.000748       1   
2       0.001807      0.000394         0.000800        0.000400      10   
3       0.003130      0.006260         0.000000        0.000000      10   
4       0.000000      0.000000         0.000000        0.000000      20   
5       0.003120      0.006241         0.003125        0.006250      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}                1.0   
1       linear   {'C': 1, 'kernel': 'linear'}                1.0   
2          rbf     {'C': 10, 'kernel': 'rbf'}                1.0   
3       linear  {'C': 10, 'kernel': 'linear'}                1.0   
4          rbf     {'C': 20, 'kernel': 'rbf'}                1.0   
5       linear  {'C': 20, 'kernel': 'linear'}                1.0   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.958333                1.0           0.916667                1.0   
1           0.958333                1.0           0.875000                1.0   
2           0.958333                1.0           0.916667                1.0   
3           0.958333                1.0           0.916667                1.0   
4           0.958333                1.0           0.916667                1.0   
5           0.916667                1.0           0.916667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.975000        0.033333                1  
1         0.966667        0.048591                5  
2         0.975000        0.033333                1  
3         0.975000        0.033333                1  
4         0.975000        0.033333                1  
5         0.966667        0.040825                6

In [146]:
data[['param_C','param_kernel','mean_test_score']]
#data[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.975000
1       1       linear         0.966667
2      10          rbf         0.975000
3      10       linear         0.975000
4      20          rbf         0.975000
5      20       linear         0.966667

In [150]:
dir(gscv)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'feature_names_in_',
 'fit',
 'get_params',
 'inverse_transform',
 

In [152]:
gscv.best_score_

0.975

In [187]:
gscv.best_params_

{'C': 5}

In [189]:
from sklearn.model_selection import RandomizedSearchCV
rmcv = RandomizedSearchCV(svm.SVC(gamma = 'auto'), {
    'C' : [1, 10, 20], 
    'kernel' :['rbf', 'linear']
    },
    cv = 5, 
    return_train_score = False, 
    n_iter = 2
    )

rmcv = RandomizedSearchCV(svm.SVC(gamma = 'auto'), {
    'C':[1, 10, 20], 
    'kernel' : ['rbf', 'linear']
    },
    cv = 5, 
    return_train_score = False, 
    n_iter = 2
    )
rmcv.fit(iris.data, iris.target)

pd.DataFrame(rmcv.cv_results_) [['param_C', 'param_kernel', 'mean_test_score']]


param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1       1       linear         0.980000

In [159]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [160]:
dff_model = {
    'svm' :{
        'model': svm.SVC(gamma = 'auto'),
        'params': {
            'C': [1, 10, 20], 
            'kernel': ['kernel', 'rbf']
        }
    }, 
    'random_forest': {
        'model': RandomForestClassifier(), 
         'params': {
             'n_estimators': [1, 5, 10]
         }
        
    }, 
    'logistic_regression': {
        'model': LogisticRegression(solver = 'liblinear', multi_class = 'auto'), 
        'params':{
            'C': [1, 5, 10]
        }

    }
          
}

In [171]:
from sklearn.model_selection import GridSearchCV
scores = []

for model_name, prm in dff_model.items():
    gscv = GridSearchCV(prm['model'], prm['params'], cv = 5, return_train_score = False)
    gscv.fit(iris.data, iris.target)
    scores.append({
        'model': model_name, 
        'best_score':gscv.best_score_, 
        'best_model':gscv.best_params_
    })
    
scores
    

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_base.py", line 180, in fit
    self._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklea

[{'model': 'svm',
  'best_score': 0.9800000000000001,
  'best_model': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': 0.9533333333333334,
  'best_model': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': 0.9666666666666668,
  'best_model': {'C': 5}}]

In [164]:
data = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])

In [165]:
data

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.973333       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}